version: 0.2

phases:
  install:
    commands:
      - apt-get install unzip
      - wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - unzip terraform_0.11.13_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version 
      - curl http://169.254.169.254/latest/meta-data/iam/security-credentials/codebuild-terraform-test-service-role
  build:
    commands:
      - echo Initializing terraform
      - terraform init
      - echo Applying terraform build
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Build completed on `date`
